version: '2.3'

services:
  backend:
    build:
      dockerfile: ./docker_images/app.dockerfile
      context: ./
    env_file:
      - ./docker_images/app.env
    depends_on:
      - db
    mem_limit: 300000000
    memswap_limit: 350000000
    mem_reservation: 250m
    cpu_count: 1
    cpu_percent: 20
    cpus: 0.5

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  jmeter:
    build:
      dockerfile: ./docker_images/jmeter.dockerfile
      context: ./
    tty: true
    depends_on: 
      - db

  app:
    build: 
      dockerfile: ./docker_images/nginx.dockerfile
      context: ./
    links:
      - backend
    ports:
      - '3000:8080'
